name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.0-preview.7
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./release/arm64 -r linux-arm64 --self-contained true
#    - name: Release
#      uses: fnkr/github-action-ghr@v1
#      if: startsWith(github.ref, 'refs/tags/')
#      env:
#        GHR_COMPRESS: zip
#        GHR_PATH: build/
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
